spring:
  application:
    name: final-eureka

server:
  port: 8010
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
    healthcheck:
      enabled: true
