server:
  port: 8030

eureka:
  instance:
    prefer-ip-address: true #使用IP注册
    #instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/

spring:
  #profiles: dev
  application:
    name: auth-client
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    user:
      jdbc-url: jdbc:mysql://192.168.0.110:3306/yugh?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver
    goods:
      jdbc-url: jdbc:mysql://192.168.0.110:3306/sys?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver

  #spring:
    #profiles: test
      #datasource:
        #  user:
        #    jdbc-url:
        #   username:
        #  password:
      #  driverClassName:
        # goods:
        #  jdbc-url:
        #  username:
        #  password:
      #  driverClassName:

    #缓存
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379

#配置调度
#

# JWT
jwt:
  header: Authorization
  secret: authSecret
  #token有效期一天
  #expiration: 86400
  expiration: 604800
  tokenHead: "token "