spring:
  application:
    name: ddd-eureka

server:
  port: 8010
eureka:
  server:
    #关闭注册中心的保护机制,踢出有问题的实例
    enable-self-preservation: false
    #清理任务程序被唤醒的时间间隔（毫秒）
    eviction-interval-timer-in-ms: 60000
  client:
    #将自己注册到注册中心
    register-with-eureka: false
    #获取注册信息
    fetch-registry: false
    serviceUrl:
      #主注册中心地址
      defaultZone: http://localhost:${server.port}/eureka/
    #healthcheck:
     # enabled: true
