server:
  port: 8040
  servlet:
    context-path: /auth-service


eureka:
  instance:
    prefer-ip-address: true #使用IP注册
    #instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      #defaultZone: http://localhost:8010/eureka/
      defaultZone: http://${EUREKA_HOST:10.16.208.24}:${EUREKA_PORT:6200}/eureka/

spring:
  application:
    name: auth-service
  datasource:
    #user:
      url: jdbc:mysql://localhost:3306/yugh?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
      username: root
      password: mac12345
      driverClassName: com.mysql.cj.jdbc.Driver
